services:
  - type: web
    name: chatbot-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --preload --max-requests 1000 --max-requests-jitter 100
    autoDeploy: true
